{% set name = "chime" %}
{% set version = "0.8.0" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chime-{{ version }}.tar.gz
  sha256: fdba6a5e96302ace7b03108b2e63808fa3152a1cda132d558f27352776f83e4b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - chime=chime:main

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - chime
  commands:
    - pip check
    - chime -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MaxHalford/chime
  summary: Python sound notifications made easy.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
