{% set name = "chime" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chime-{{ version }}.tar.gz
  sha256: ba4af8934ec8bd9a89a340b4433b2e500097b979823386432be7128e0b201f0d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - chime=chime:main

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - chime
  commands:
    - pip check
    - chime -h
  requires:
    - pip

about:
  home: https://github.com/MaxHalford/chime
  summary: Python sound notifications made easy.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
